### ISSUE TITLE
Bugs in Absplice implementation

### ISSUE THREAD

**Issue by knakamura6222053** [gagneurlab/absplice#12]
Dear Dr. Gagneur.

We are also working on the implementation of the Absplice reported in this issue.
However, I have been working on it based on the readme at the following URL, but an error occurred in the test sample.
I would like to know what to do in this case.

The command that caused the error is as follows
python -m snakemake -j 1 --use-conda

The following is the ERROR message.

Error in rule download_splicemaps:
    jobid: 4
    output: splicemap_gtex_v8
    shell:
        splicemap_download --version gtex_v8 --splicemap_dir splicemap_gtex_v8 --tissues Testis --tissues Cells_Cultured_fibroblasts
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-05-17T141553.827340.snakemake.log

**Comment by neverov-am** [comment]
Dear Kouta,

thank you for your question.

It seems like the module splicemap is not installed in the environment. In order to install it you can use

pip install git+https://github.com/gagneurlab/splicemap.git

However, further issues might occur because you are likely using a previous version of AbSplice. We updated the AbSplice GitHub repository recently, and we would recommend you to pull changes by running git pull in your AbSplice repository first, and then create the environment again.

Please feel free to check the updated AbSplice repository: https://github.com/gagneurlab/absplice/

If any further issues appear, please feel free to contact us again.

**Comment by Aikaterini-Chatzipli** [comment]
Hello AbSplice developers, 

I have been having issues implementing AbSplice too - even after the latest installation update. I got an error message regarding module 'cyvcf2'. I installed cyvcf2 in three different ways but I got the same error every time. Please see the message below. Could you please advise on how to fix the error?

Many thanks, 

Aikaterini

RuleException:
ModuleNotFoundError in file /n/data/absplice/example/Snakefile, line 150:
No module named 'cyvcf2'
  File "/n/data/absplice/example/Snakefile", line 150, in __rule_spliceai_vcf_to_csv
  File "/n/data/absplice/absplice/utils.py", line 129, in read_spliceai_vcf
  File "/home/k/.local/lib/python3.10/site-packages/kipoiseq/extractors/vcf.py", line 24, in __init__
  File "/n/app/python/3.10.11.conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by knakamura6222053** [comment]
Hello AbSplice developers,

Please feel free to check the updated AbSplice repository: (https://github.com/gagneurlab/absplice/)

> I try it but 「conda env create -f environment.yaml」don't success.

Please check it

Best regards

**Comment by Aikaterini-Chatzipli** [comment]
I checked out the updated repository and I re-installed AbSplice but I am experiencing the same issue as before. The actual example you provide doesn't work. Line, python -m snakemake -j 1 --use-conda , still produces the error message below. 

Thank you, 

Aikaterini


RuleException:
ModuleNotFoundError in file /n/data/absplice/example/Snakefile, line 150:
No module named 'cyvcf2'
File "/n/data/absplice/example/Snakefile", line 150, in __rule_spliceai_vcf_to_csv
File "/n/data/absplice/absplice/utils.py", line 129, in read_spliceai_vcf
File "/home/k/.local/lib/python3.10/site-packages/kipoiseq/extractors/vcf.py", line 24, in init
File "/n/app/python/3.10.11.conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by neverov-am** [comment]
Dear @Aikaterini-Chatzipli,

Thank you for your question.
Did you get any error message from conda after running 'create env -f environment.yaml'?
Could you kindly provide it here?

Dear @knakamura6222053,

Could you also kindly provide us with an error message you are getting?

**Comment by Aikaterini-Chatzipli** [comment]
No, I didn't get an error when I run 'create env -f environment.yaml'

Thank you, 

Aikaterini

**Comment by knakamura6222053** [comment]
Dear @ neverov-am,

 I didn't receive any error message, but 「conda env create -f environment.yam」don't finish.

**Comment by WagnerNils** [comment]
Thanks for reporting this. There has been a bug report related to the last release of cyvcf2 and conda: https://github.com/brentp/cyvcf2/issues. What version of cyvcf2 do you have in your conda environment (can you print `conda list | grep cyvcf2`)? I fixed the version to an earlier release in the environment.yaml. Let me know if this resolves the issue for you.

**Comment by knakamura6222053** [comment]
I tried conda list | grep cyvcf2 but nothing is returned.
Therefore, I reinstalled it again. However, the installation is failing.

**Comment by knakamura6222053** [comment]
Here is a summary of my current situation.
I am currently using MacOS.


I downloaded the newly updated Absplice again, but the conda env create -f environment.yaml is stopping without error.
I re-installed cyvcf2. However, I get an error there and the installation is not working.

So instead of doing conda env create -f environment.yaml, I did a python setup.py install and
pip install -e .
and obtained the necessary modules.
After that,
cd example
python -m snakemake -j 1 --use-conda

Now I further tried pip3 install snakemake.
When I did so, I got the following error
Is there any good way to improve it?



(base) IDRCnoMacBook-Pro:example idrc$ pip3 install snakemake
Requirement already satisfied: snakemake in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/snakemake-7.25.2-py3.9.egg (7.25.2)
Requirement already satisfied: appdirs in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (1.4.4)
Requirement already satisfied: configargparse in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (1.5.3)
Collecting connection-pool>=0.0.3 (from snakemake)
  Using cached connection_pool-0.0.3-py3-none-any.whl
Collecting datrie (from snakemake)
  Using cached datrie-0.8.2.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: docutils in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (0.18.1)
Requirement already satisfied: gitpython in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/GitPython-3.1.31-py3.9.egg (from snakemake) (3.1.31)
Requirement already satisfied: humanfriendly in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/humanfriendly-10.0-py3.9.egg (from snakemake) (10.0)
Collecting jinja2<4.0,>=3.0 (from snakemake)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: jsonschema in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (3.2.0)
Requirement already satisfied: nbformat in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (5.5.0)
Requirement already satisfied: psutil in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (5.9.0)
Requirement already satisfied: pulp>=2.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/PuLP-2.7.0-py3.9.egg (from snakemake) (2.7.0)
Requirement already satisfied: pyyaml in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (5.4.1)
Requirement already satisfied: requests in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (2.28.1)
Requirement already satisfied: reretry in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/reretry-0.11.8-py3.9.egg (from snakemake) (0.11.8)
Requirement already satisfied: smart-open>=3.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (5.2.1)
Requirement already satisfied: stopit in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/stopit-1.1.2-py3.9.egg (from snakemake) (1.1.2)
Requirement already satisfied: tabulate in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (0.8.10)
Requirement already satisfied: throttler in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/throttler-1.2.2-py3.9.egg (from snakemake) (1.2.2)
Requirement already satisfied: toposort>=1.10 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/toposort-1.10-py3.9.egg (from snakemake) (1.10)
Requirement already satisfied: wrapt in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from snakemake) (1.14.1)
Requirement already satisfied: yte<2.0,>=1.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages/yte-1.5.1-py3.9.egg (from snakemake) (1.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from jinja2<4.0,>=3.0->snakemake) (2.0.1)
Collecting dpath<3.0,>=2.0 (from yte<2.0,>=1.0->snakemake)
  Using cached dpath-2.1.6-py3-none-any.whl (17 kB)
Collecting plac<2.0.0,>=1.3.4 (from yte<2.0,>=1.0->snakemake)
  Using cached plac-1.3.5-py2.py3-none-any.whl (22 kB)
Collecting pyyaml (from snakemake)
  Using cached PyYAML-6.0-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython->snakemake)
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
Requirement already satisfied: attrs>=17.4.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from jsonschema->snakemake) (21.4.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from jsonschema->snakemake) (0.18.0)
Requirement already satisfied: setuptools in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from jsonschema->snakemake) (67.6.0)
Requirement already satisfied: six>=1.11.0 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from jsonschema->snakemake) (1.16.0)
Requirement already satisfied: fastjsonschema in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from nbformat->snakemake) (2.16.2)
Requirement already satisfied: jupyter_core in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from nbformat->snakemake) (4.11.1)
Requirement already satisfied: traitlets>=5.1 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from nbformat->snakemake) (5.1.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from requests->snakemake) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from requests->snakemake) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from requests->snakemake) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/idrc/opt/anaconda3/lib/python3.9/site-packages (from requests->snakemake) (2023.5.7)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->snakemake)
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Building wheels for collected packages: datrie
  Building wheel for datrie (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for datrie (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running bdist_wheel
      running build
      running build_clib
      building 'datrie' library
      creating build
      creating build/temp.macosx-10.9-x86_64-cpython-39
      creating build/temp.macosx-10.9-x86_64-cpython-39/libdatrie
      creating build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/alpha-map.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/alpha-map.o
      libdatrie/datrie/alpha-map.c:500:21: warning: comparison of integers of different signs: 'TrieIndex' (aka 'int') and 'AlphaChar' (aka 'unsigned int') [-Wsign-compare]
          if (alpha_begin <= ac && ac <= alpha_map->alpha_end)
              ~~~~~~~~~~~ ^  ~~
      1 warning generated.
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/darray.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/darray.o
      libdatrie/datrie/darray.c:239:22: warning: comparison of integers of different signs: 'TrieIndex' (aka 'int') and 'unsigned long' [-Wsign-compare]
          if (d->num_cells > SIZE_MAX / sizeof (DACell))
              ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
      1 warning generated.
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/dstring.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/dstring.o
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/fileutils.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/fileutils.o
      libdatrie/datrie/fileutils.c:103:52: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
          return (fread (buff, sizeof (char), len, file) == len);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~
      libdatrie/datrie/fileutils.c:109:53: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
          return (fwrite (buff, sizeof (char), len, file) == len);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~
      2 warnings generated.
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/tail.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/tail.o
      libdatrie/datrie/tail.c:144:22: warning: comparison of integers of different signs: 'TrieIndex' (aka 'int') and 'unsigned long' [-Wsign-compare]
          if (t->num_tails > SIZE_MAX / sizeof (TailBlock))
              ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      1 warning generated.
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/trie-string.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/trie-string.o
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -I/Users/idrc/opt/anaconda3/include -fPIC -O2 -isystem /Users/idrc/opt/anaconda3/include -arch x86_64 -Ilibdatrie -c libdatrie/datrie/trie.c -o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/trie.o
      /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_aafi60xe3m/croots/recipe/python-split_1661469468466/_build_env/bin/llvm-ar rcs build/temp.macosx-10.9-x86_64-cpython-39/libdatrie.a build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/alpha-map.o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/darray.o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/dstring.o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/fileutils.o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/tail.o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/trie-string.o build/temp.macosx-10.9-x86_64-cpython-39/libdatrie/datrie/trie.o
      error: command '/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_aafi60xe3m/croots/recipe/python-split_1661469468466/_build_env/bin/llvm-ar' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for datrie
Failed to build datrie
ERROR: Could not build wheels for datrie, which is required to install pyproject.toml-based projects

**Comment by Aikaterini-Chatzipli** [comment]
I reinstalled AbSplice and I tried "conda list | grep cyvcf2" but nothing was returned, even after reinstalling cyvcf2. 
However, I am not getting an error about "cyvcf2" anymore. Instead, I got an error for "interpret" which I initially installed and I am now getting an error for "interpret.glassbox.ebm" which persists. Please see error message below.

Thank you, 

Aikaterini

python -m snakemake -j 1 --use-conda
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job             count    min threads    max threads
------------  -------  -------------  -------------
absplice_dna        1              1              1
all                 1              1              1
total               2              1              1

Select jobs to execute...

rule absplice_dna:
    input: data/results/hg19/example.vcf.gz_mmsplice_splicemap.csv, data/results/hg19/example.vcf.gz_spliceai.csv
    output: data/results/hg19/example.vcf.gz_absplice_dna.csv
    jobid: 2
    reason: Missing output files: data/results/hg19/example.vcf.gz_absplice_dna.csv
    wildcards: genome=hg19, vcf_id=example.vcf.gz
    resources: tmpdir=/tmp

tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used. tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/n/data1/absplice/example/.snakemake/scripts/tmprpcx7ssh.absplice_dna.py", line 11, in <module>
    splicing_result.predict_absplice_dna()
  File "/n/data1/absplice/absplice/result.py", line 642, in predict_absplice_dna
    model = pickle.load(open(pickle_file, 'rb'))
ModuleNotFoundError: No module named 'interpret.glassbox.ebm'

Error in rule absplice_dna:
    jobid: 2
    input: data/results/hg19/example.vcf.gz_mmsplice_splicemap.csv, data/results/hg19/example.vcf.gz_spliceai.csv
    output: data/results/hg19/example.vcf.gz_absplice_dna.csv

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by WagnerNils** [comment]
Hi, we again updated the environment, trying to prevent package conflicts. Furthermore, we included a circleCI framework to test creating the environment and test running the example use case. It runs through in circleCI. Can you try again if it works for you now?

**Comment by Aikaterini-Chatzipli** [comment]
Hello, 

Thanks for working on the AbSplice issue I encountered. Unfortunately, I am still getting an error. Please see details below. The command causing the problem is the same as before. 

cd example/workflow
python -m snakemake -j 1 --use-conda

/n/data1/absplice/example/workflow
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...

Error in rule spliceai_vcf_to_csv:
    jobid: 0
    input: ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_SpliceAI.vcf
    output: ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_SpliceAI.csv

RuleException:
ModuleNotFoundError in file /n/data1/absplice/example/workflow/./splicing_pred/DNA/Snakefile, line 106:
No module named 'absplice'
  File "/n/data1/absplice/example/workflow/./splicing_pred/DNA/Snakefile", line 106, in __rule_spliceai_vcf_to_csv
  File "/n/app/python/3.10.11.conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by WagnerNils** [comment]
Hi, this error tells that the module 'absplice' is missing in your environment. Did you run 'pip install -e .' in the root directory of the repo (the directory that contains the setup.py file)?

**Comment by Aikaterini-Chatzipli** [comment]
Thanks, it seems I missed this step. I rerun the example including the  'pip install -e .' line and here is what I got:

Finished job 7.
6 of 8 steps (75%) done
Select jobs to execute...

rule absplice_dna:
    input: ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_MMSplice_SpliceMap.csv, ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_SpliceAI.csv
    output: ../data/results/hg19/example_hg19.vcf.gz_AbSplice_DNA.csv
    jobid: 6
    reason: Missing output files: ../data/results/hg19/example_hg19.vcf.gz_AbSplice_DNA.csv; Input files updated by another job: ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_MMSplice_SpliceMap.csv, ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_SpliceAI.csv
    wildcards: genome=hg19, vcf_id=example_hg19.vcf.gz
    resources: tmpdir=/tmp

I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/n/data1/absplice/example/workflow/.snakemake/scripts/tmpsenbgqsw.absplice_dna.py", line 11, in <module>
    splicing_result.predict_absplice_dna()
  File "/n/data1/absplice/absplice/result.py", line 679, in predict_absplice_dna
    model = pickle.load(open(pickle_file, 'rb'))
ModuleNotFoundError: No module named 'interpret.glassbox.ebm'
Error in rule absplice_dna:
    jobid: 6
    input: ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_MMSplice_SpliceMap.csv, ../data/results/hg19/model_scores_from_absplice_features/example_hg19.vcf.gz_SpliceAI.csv
    output: ../data/results/hg19/example_hg19.vcf.gz_AbSplice_DNA.csv

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by knakamura6222053** [comment]
Hello

I cannot install yet.
”conda env create -f environment.yaml ”
This is still a non-responsive situation with no error message obtained.

I try "mamba env create -f environment.yaml" but don't complie

Error message below

mamba env create -f environment.yam
Traceback (most recent call last):
  File "/Users/tauko/opt/anaconda3/bin/mamba", line 8, in <module>
    sys.exit(main())
  File "/Users/tauko/opt/anaconda3/lib/python3.9/site-packages/mamba/cli.py", line 16, in main
    runner = factory.runner()
  File "/Users/tauko/opt/anaconda3/lib/python3.9/site-packages/mamba/application_factory.py", line 46, in runner
    self._reporter(),
  File "/Users/tauko/opt/anaconda3/lib/python3.9/site-packages/mamba/application_factory.py", line 63, in _reporter
    return reporter.Reporter(self._formatter())
  File "/Users/tauko/opt/anaconda3/lib/python3.9/site-packages/mamba/application_factory.py", line 73, in _formatter
    return self._custom_formatter()
  File "/Users/tauko/opt/anaconda3/lib/python3.9/site-packages/mamba/application_factory.py", line 78, in _custom_formatter
    formatter = getattr(module, splitted[-1])
AttributeError: module 'environment' has no attribute 'yam'




Best regards

**Comment by knakamura6222053** [comment]
Hello


python -m snakemake -j 1 --use-conda
Execution of
I also did a conda install because I got an error
But it didn't solve the problem.
How can I make it work?




python -m snakemake -j 1 --use-conda

ImportError: dlopen(/Users/tauko/opt/anaconda3/lib/python3.9/site-packages/libmambapy/[bindings.cpython-39-darwin.so](http://bindings.cpython-39-darwin.so/), 0x0002): Library not loaded: '@rpath/libarchive.13.dylib'
  Referenced from: '/Users/tauko/opt/anaconda3/lib/libmamba.2.0.0.dylib'
  Reason: tried: '/Users/tauko/opt/anaconda3/lib/libarchive.13.dylib' (no such file), 
'/Users/opt/anaconda3/lib/python3.9/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/opt/anaconda3/lib/python3.9/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/opt/anaconda3/bin/../lib/libarchive.13.dylib' (no such file), '/Users/opt/anaconda3/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)
